### ISSUE TITLE
Kingress controller with Gateway APIs

### ISSUE THREAD

**Issue by ZhiminXiang** [knative-sandbox/net-ingressv2#12]
We need to implement Kingress controller with Gateway APIs so that Knative could consume Gateway APIs.

/cc @nak3 I think we still need it as the intermediate step?

**Comment by nak3** [comment]
You mean that the controller to create from Gateway API from KIngress, correct? If so, we will not create it.
Here is the discussion thread (as you might know) - https://knative.slack.com/archives/CA9RHBGJX/p1613698271156800

- phase-1. Create new networking conformance suite by Gateway API resources.
- phase-2. Create `makeIngressv2()` in serving code. (I think we should allow users to choose KIngress or Ingress v2 by some option during this migration phase.)
- phase-3. Deprecate `makeIngress()` in serving code.

**Comment by ZhiminXiang** [comment]
I read the thread again. sounds like we don't need the ingress v2 controller.

Then about the phases, here is what I read from the chat thread:
* Phase 1:  Create makeIngressv2() in knative serving code with a feature flag
* Phase 2: testing serving E2E tests with makeIngressv2() enabled for all impls
* Phase 3: deprecate makeIngress

I am not very sure what we plan to do about "Create new networking conformance suite by Gateway API resources" mentioned in above comment. Do we plan to add conformance test suites within net-ingressv2 to cover all knative networking scenarios, or only basic test suites like https://github.com/knative-sandbox/net-ingressv2/pull/10/files#diff-dd6583ae8832b447f778694426e7a1a3f9da8de2ce0991ebfaad75935c87d6d5 for basic sanity check? Could we just skip this phase considering that we may want to run all E2E tests with makeIngressv2 enabled for all impls?

cc @markusthoemmes

**Comment by ZhiminXiang** [comment]
Thought about this again. I think the value of the work `Create new networking conformance suite by Gateway API resources.` is to provide various impls the handy conformance check for the ingress v2 to support knative. So if the work could be landed more easily and quickly, I think we can start with this one.

**Comment by nak3** [comment]
Yes, not only handy conformance check for the ingress v2 providers, but also serving's e2e tests do not cover all networking features so we need the "Create new networking conformance suite by Gateway API resources" which can cover current KIngress tests by ingress v2.

Also, we plan to add all conformance tests. I just added basic test only here https://github.com/knative-sandbox/net-ingressv2/pull/10 because creating all test suites needs "man-power". I think I just add a basic test and common utils in https://github.com/knative-sandbox/net-ingressv2/pull/10, then will ask some volunteers to add other tests.
